CREATE TABLE departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(100) NOT NULL UNIQUE
);


CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Human-facing Employee ID used for login.
    -- Example: EMP001
                           employee_id VARCHAR(20) NOT NULL UNIQUE,

                           full_name VARCHAR(150) NOT NULL,
                           email VARCHAR(150) NOT NULL UNIQUE,
                           designation VARCHAR(100) NOT NULL,

                           department_id BIGINT NOT NULL,

    -- Direct manager. References another employee.
                           manager_id BIGINT,

                           date_of_joining DATE NOT NULL,

                           active BOOLEAN NOT NULL DEFAULT TRUE,

                           created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_employee_department
                               FOREIGN KEY (department_id)
                                   REFERENCES departments(id),

                           CONSTRAINT fk_employee_manager
                               FOREIGN KEY (manager_id)
                                   REFERENCES employees(id),

                           CONSTRAINT chk_employee_not_own_manager
                               CHECK (manager_id IS NULL OR manager_id <> id)
);


CREATE TABLE employee_credentials (
    -- References employees.id, NOT the value EMP001.
                                      employee_ref_id BIGINT PRIMARY KEY,

    -- BCrypt encoded password.
                                      password_hash VARCHAR(100) NOT NULL,

                                      enabled BOOLEAN NOT NULL DEFAULT TRUE,

                                      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT fk_credentials_employee
                                          FOREIGN KEY (employee_ref_id)
                                              REFERENCES employees(id)
);


CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                employee_ref_id BIGINT NOT NULL,

    -- Store the hash of the refresh token, never the raw token.
                                token_hash VARCHAR(64) NOT NULL UNIQUE,

                                expires_at TIMESTAMPTZ NOT NULL,

    -- Set when the refresh token is used during rotation
    -- or invalidated during logout.
                                revoked_at TIMESTAMPTZ,

    -- When R1 is rotated into R2,
    -- R1.replaced_by_token_id points to R2.
                                replaced_by_token_id BIGINT,

                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_refresh_token_employee
                                    FOREIGN KEY (employee_ref_id)
                                        REFERENCES employees(id),

                                CONSTRAINT fk_refresh_token_replacement
                                    FOREIGN KEY (replaced_by_token_id)
                                        REFERENCES refresh_tokens(id),

                                CONSTRAINT chk_refresh_token_expiry
                                    CHECK (expires_at > created_at),

                                CONSTRAINT chk_refresh_token_not_self_replacement
                                    CHECK (
                                        replaced_by_token_id IS NULL
                                            OR replaced_by_token_id <> id
                                        )
);


CREATE INDEX idx_employees_department
    ON employees(department_id);


CREATE INDEX idx_employees_manager
    ON employees(manager_id);


CREATE INDEX idx_refresh_tokens_employee
    ON refresh_tokens(employee_ref_id);