CREATE TABLE leave_balances (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                employee_ref_id BIGINT NOT NULL,
                                leave_type VARCHAR(20) NOT NULL,
                                balance_year SMALLINT NOT NULL,

                                entitled_days SMALLINT NOT NULL,
                                carried_forward_days SMALLINT NOT NULL DEFAULT 0,
                                used_days SMALLINT NOT NULL DEFAULT 0,
                                reserved_days SMALLINT NOT NULL DEFAULT 0,

                                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_leave_balance_employee
                                    FOREIGN KEY (employee_ref_id)
                                        REFERENCES employees(id),

                                CONSTRAINT uq_employee_leave_balance
                                    UNIQUE (employee_ref_id, leave_type, balance_year),

                                CONSTRAINT chk_leave_balance_type
                                    CHECK (leave_type IN ('ANNUAL', 'CASUAL', 'SICK')),

                                CONSTRAINT chk_leave_balance_values
                                    CHECK (
                                        entitled_days >= 0
                                            AND carried_forward_days >= 0
                                            AND used_days >= 0
                                            AND reserved_days >= 0
                                        ),

                                CONSTRAINT chk_leave_balance_available
                                    CHECK (
                                        used_days + reserved_days
                                            <= entitled_days + carried_forward_days
                                        ),

                                CONSTRAINT chk_leave_balance_carry_forward
                                    CHECK (
                                        leave_type = 'ANNUAL'
                                            OR carried_forward_days = 0
                                        )
);


CREATE TABLE leave_requests (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                employee_ref_id BIGINT NOT NULL,

                                leave_type VARCHAR(20) NOT NULL,

                                start_date DATE NOT NULL,
                                end_date DATE NOT NULL,

    -- Calculated by backend after excluding weekends and company holidays
                                working_days SMALLINT NOT NULL,

                                status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                                reason VARCHAR(500),

                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_leave_request_employee
                                    FOREIGN KEY (employee_ref_id)
                                        REFERENCES employees(id),

                                CONSTRAINT chk_leave_request_type
                                    CHECK (
                                        leave_type IN (
                                                       'ANNUAL',
                                                       'CASUAL',
                                                       'SICK',
                                                       'UNPAID'
                                            )
                                        ),

                                CONSTRAINT chk_leave_request_status
                                    CHECK (
                                        status IN (
                                                   'PENDING',
                                                   'APPROVED',
                                                   'REJECTED',
                                                   'CANCELLED',
                                                   'COMPLETED'
                                            )
                                        ),

                                CONSTRAINT chk_leave_request_dates
                                    CHECK (end_date >= start_date),

                                CONSTRAINT chk_leave_request_working_days
                                    CHECK (working_days > 0)
);


CREATE TABLE leave_approvals (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 leave_request_id BIGINT NOT NULL,

    -- NULL for system auto-approval
                                 approver_ref_id BIGINT,

                                 approval_type VARCHAR(30) NOT NULL,

    -- 1 = first approver, 2 = next approver, etc.
                                 sequence_no SMALLINT NOT NULL,

                                 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                                 decision_reason VARCHAR(500),

                                 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 acted_at TIMESTAMPTZ,

                                 CONSTRAINT fk_leave_approval_request
                                     FOREIGN KEY (leave_request_id)
                                         REFERENCES leave_requests(id),

                                 CONSTRAINT fk_leave_approval_employee
                                     FOREIGN KEY (approver_ref_id)
                                         REFERENCES employees(id),

                                 CONSTRAINT chk_leave_approval_type
                                     CHECK (
                                         approval_type IN (
                                                           'AUTO',
                                                           'DIRECT_MANAGER',
                                                           'SECOND_LEVEL_MANAGER',
                                                           'HR'
                                             )
                                         ),

                                 CONSTRAINT chk_leave_approval_status
                                     CHECK (
                                         status IN (
                                                    'PENDING',
                                                    'APPROVED',
                                                    'REJECTED'
                                             )
                                         ),

                                 CONSTRAINT chk_leave_approval_sequence
                                     CHECK (sequence_no > 0),

                                 CONSTRAINT chk_auto_approval_approver
                                     CHECK (
                                         (approval_type = 'AUTO' AND approver_ref_id IS NULL)
                                             OR
                                         (approval_type <> 'AUTO' AND approver_ref_id IS NOT NULL)
                                         ),

                                 CONSTRAINT uq_leave_approval_sequence
                                     UNIQUE (leave_request_id, sequence_no)
);


CREATE TABLE leave_attachments (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   leave_request_id BIGINT NOT NULL,

                                   attachment_type VARCHAR(30) NOT NULL,

                                   file_name VARCHAR(255) NOT NULL,
                                   content_type VARCHAR(100) NOT NULL,

    -- Actual PDF/JPG/PNG bytes
                                   file_data BYTEA NOT NULL,

                                   uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_leave_attachment_request
                                       FOREIGN KEY (leave_request_id)
                                           REFERENCES leave_requests(id),

                                   CONSTRAINT chk_leave_attachment_type
                                       CHECK (
                                           attachment_type IN ('MEDICAL_CERTIFICATE')
                                           )
);


CREATE TABLE company_holidays (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  holiday_date DATE NOT NULL UNIQUE,
                                  name VARCHAR(100) NOT NULL
);


CREATE INDEX idx_leave_balances_employee
    ON leave_balances(employee_ref_id);


CREATE INDEX idx_leave_requests_employee_status
    ON leave_requests(employee_ref_id, status);


CREATE INDEX idx_leave_approvals_approver_status
    ON leave_approvals(approver_ref_id, status);


CREATE INDEX idx_leave_attachments_request
    ON leave_attachments(leave_request_id);